spring.application.name=supmeal-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/supmeal
spring.datasource.username=postgres
spring.datasource.password=al99al

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true