spring.application.name=supmeal-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/supmeal
spring.datasource.username=postgres
spring.datasource.password=al99al

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=c3VwbWVhbFNlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvblNob3VsZEJlVmVyeUxvbmdBbmRTZWN1cmU=
jwt.expiration=86400000

# File upload configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB